export class Institution {
    constructor(
        public id: number = 0,
        public cityId: number = 0,
        public userId: number = 0,
        public createDate: Date = new Date(),
        public name: string = '',
        public cnpj: string = '',
        public website: string = '',
        public email: string = '',
        public enable: boolean = false,
        public smsUser: string = '',
        public smsPassword: string = '',
        public smsEnable: boolean = false,
        public prefix: string = '',
        public acronymGraphic: string = '',
        public tcmCode: string = '',
        public organizationTypeId: number = 0,
        public initialYear: number = 0,
        public finalYear: number = 0,
        public code: string = '',
        public address: string = '',
        public reportName: string = '',
        public taxManagement: boolean = false,
        public cnaeCode: string = '',
        public consolidationNumber: string = '',
        public phoneNumber: string = '',
        public neighborhood: string = '',
        public zipCode: string = '',
        public number: string = '',
        public institutionDefault: boolean = false,
        public lastProcessNumber: number = 0,
        public permitHealthRequest: boolean = false,
        public issRetained: boolean = false,
        public percentageFap: number = 0,
        public percentageRat: number = 0,
        public ddd: string = '',
        public complementAddress: string = '',
        public cei: string = '',
        public legalNature: string = '',
        public codeUnitManager: string = '',
        public observationScreenInitialNfse: string = '',
        public colareId: number = 0,
        public managementUnitId: number = 0,
        public typeResponsibleManagementUnit: number = 0,
        public titleMessageIss: string = '',
        public paragraphOne: string = '',
        public paragraphTwoo: string = '',
        public paragraphThree: string = '',
        public idInstituicaoMatrix: number = 0,
        public siafi: string = '',
        public ignoreTceMa: boolean = false,
        public descendingProcessFile: boolean = false,
        public socialIdTableEstablishment: number = 0,
        public disablePortal: boolean = false,
    ) {
    }
}